// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'YOUR_WEB_API_KEY'),
    appId: '1:91877163003:web:b50d7973de430817d4d55e',
    messagingSenderId: '91877163003',
    projectId: 'cashfit-2800f',
    authDomain: 'cashfit-2800f.firebaseapp.com',
    storageBucket: 'cashfit-2800f.firebasestorage.app',
    measurementId: 'G-0D49JCNNVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_ANDROID_API_KEY', defaultValue: 'YOUR_ANDROID_API_KEY'),
    appId: '1:91877163003:android:12c84219d8ce391ad4d55e',
    messagingSenderId: '91877163003',
    projectId: 'cashfit-2800f',
    storageBucket: 'cashfit-2800f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'YOUR_IOS_API_KEY'),
    appId: '1:91877163003:ios:aec10b5946bc8b72d4d55e',
    messagingSenderId: '91877163003',
    projectId: 'cashfit-2800f',
    storageBucket: 'cashfit-2800f.firebasestorage.app',
    iosBundleId: 'com.example.cashfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_IOS_API_KEY', defaultValue: 'YOUR_IOS_API_KEY'),
    appId: '1:91877163003:ios:aec10b5946bc8b72d4d55e',
    messagingSenderId: '91877163003',
    projectId: 'cashfit-2800f',
    storageBucket: 'cashfit-2800f.firebasestorage.app',
    iosBundleId: 'com.example.cashfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_WEB_API_KEY', defaultValue: 'YOUR_WEB_API_KEY'),
    appId: '1:91877163003:web:a5d25143890c13e5d4d55e',
    messagingSenderId: '91877163003',
    projectId: 'cashfit-2800f',
    authDomain: 'cashfit-2800f.firebaseapp.com',
    storageBucket: 'cashfit-2800f.firebasestorage.app',
    measurementId: 'G-Q8VYNBFN9P',
  );
}
